### ISSUE TITLE
Do constraint versions of the standard ordering comparisons `@>` etc make sense?

### ISSUE THREAD

**Issue by jasonhemann** [bakaq/constrained.pl#17]
I was also wondering about variants that might respect the clpz notion of inequalities on numbers.

**Comment by bakaq** [comment]
`(@>)/2` and friends don't make much sense because they also order variables, which breaks monotonicity pretty hard. The only way I think it's possible to make that make sense is to constrain them to work on ground terms, and throw a instantiation error otherwise. Seems doable actually.

For `library(clpz)`, well, just use `library(clpz)`. I tried to integrate with it as best as I could.
